### ISSUE TITLE
Inter VM rules should be an address range rather than an IP address

### ISSUE THREAD

**Issue by drmatthews** [UCL-MIRSG/ansible-role-firewalld#9]
At the moment the "[Allow inter-vm connections](https://github.com/UCL-MIRSG/ansible-role-firewalld/blob/7ccce9d728facb2cd1a92dc4da1e7d6371d4e58a/tasks/main.yml#L43)" task hard-wires the address range so that a single IP address is used ("/32") and an IP is passed as a variable. This should accept an address range as a variable instead.

Proposed change from:

```
- name: Allow inter-vm connections
  become: true
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 source address={{ item.ip }}/32 port protocol=tcp port={{ item.port }} accept"
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ inter_vm_rules }}"
  when: allow_inter_vm_connections
```

To:

```
- name: Allow inter-vm connections
  become: true
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 source address={{ item.address }} port protocol=tcp port={{ item.port }} accept"
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ inter_vm_rules }}"
  when: allow_inter_vm_connections
```
